import { StyleSheet } from 'react-native';

import { colors, radius, spacing, typography } from '@/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.neutral,
  },
  pressed: {
    transform: [{ scale: 0.98 }],
    opacity: 0.88,
  },
  surface: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
  },
  paperSurface: {
    backgroundColor: colors.paper,
    borderColor: colors.paperEdge,
  },
  raisedSurface: {
    backgroundColor: colors.surfaceElevated,
  },
  appMark: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  appMarkImage: {
    height: 32,
    width: 32,
  },
  appMarkText: {
    color: colors.primaryPressed,
    fontSize: 28,
    fontWeight: '700',
    lineHeight: 32,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceElevated,
    borderColor: colors.border,
    borderRadius: 20,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  iconButtonFilled: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  iconButtonText: {
    ...typography.labelLg,
    color: colors.ink,
    lineHeight: 18,
  },
  authScreen: {
    alignSelf: 'center',
    flexGrow: 1,
    gap: spacing.xl,
    maxWidth: 430,
    paddingHorizontal: spacing.screen,
    paddingTop: spacing.xl,
    paddingBottom: spacing.xxl,
    width: '100%',
  },
  authTop: {
    alignItems: 'flex-start',
    paddingTop: spacing.sm,
  },
  authHero: {
    gap: spacing.xxxl,
  },
  authMark: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  authMarkText: {
    ...typography.titleMd,
    color: colors.primary,
  },
  authCopy: {
    gap: spacing.lg,
  },
  authIntro: {
    gap: spacing.lg,
    paddingTop: spacing.xxxl,
  },
  authBrand: {
    ...typography.labelLg,
    color: colors.secondary,
  },
  authTitle: {
    fontSize: 46,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 52,
    color: colors.onSurface,
    maxWidth: 318,
  },
  authTitleSlot: {
    color: colors.onSurface,
  },
  authBody: {
    fontSize: 16,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 23,
    color: colors.onMuted,
    maxWidth: 292,
  },
  authPreviewWrap: {
    alignItems: 'center',
    overflow: 'hidden',
    paddingTop: spacing.xl,
    width: '100%',
  },
  authActions: {
    gap: spacing.md,
  },
  authGoogleButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    flexDirection: 'row',
    gap: spacing.xl,
    maxWidth: 292,
    minHeight: 56,
    paddingHorizontal: spacing.xl,
    width: '100%',
  },
  authGoogleGlyphText: {
    color: colors.onPrimary,
    fontSize: 30,
    fontWeight: '700',
    lineHeight: 34,
  },
  authGoogleButtonText: {
    fontSize: 16,
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 20,
    color: colors.onPrimary,
    flex: 1,
    textAlign: 'left',
  },
  authAppleButton: {
    alignItems: 'center',
    backgroundColor: '#000000',
    borderRadius: radius.md,
    flexDirection: 'row',
    gap: spacing.xl,
    maxWidth: 292,
    minHeight: 56,
    paddingHorizontal: spacing.xl,
    width: '100%',
  },
  authAppleGlyphText: {
    color: '#FFFFFF',
    fontSize: 30,
    fontWeight: '700',
    lineHeight: 34,
  },
  authAppleButtonText: {
    fontSize: 16,
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 20,
    color: '#FFFFFF',
    flex: 1,
    textAlign: 'left',
  },
  authProviderGroup: {
    gap: spacing.md,
    width: '100%',
    alignItems: 'center',
  },
  authPendingRow: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    borderTopColor: colors.border,
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: spacing.md,
    maxWidth: 292,
    paddingVertical: spacing.sm,
  },
  authPendingCopy: {
    flex: 1,
    gap: spacing.xxs,
    minWidth: 0,
  },
  authPendingTitle: {
    ...typography.labelMd,
    color: colors.secondary,
  },
  authPendingUrl: {
    ...typography.caption,
    color: colors.onMuted,
  },
  authPendingAction: {
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
  },
  authPendingActionText: {
    ...typography.labelMd,
    color: colors.primary,
  },
  authFooter: {
    alignItems: 'center',
    marginTop: 'auto',
  },
  authLink: {
    alignSelf: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  authLinkText: {
    ...typography.labelMd,
    color: colors.secondary,
  },
  topNav: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  navBrand: {
    ...typography.titleMd,
    color: colors.primaryPressed,
  },
  navActions: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  navSquareButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  navButtonText: {
    ...typography.labelLg,
    color: colors.onSurface,
  },
  profileButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 19,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  profileButtonText: {
    ...typography.labelLg,
    color: colors.onPrimary,
  },
  homeContent: {
    alignSelf: 'center',
    gap: spacing.lg,
    maxWidth: 430,
    padding: spacing.screen,
    paddingBottom: spacing.xxl,
    width: '100%',
  },
  homeHeader: {
    gap: spacing.sm,
    paddingTop: spacing.sm,
  },
  screenTitle: {
    ...typography.headlineLg,
    color: colors.onSurface,
  },
  screenSubtitle: {
    ...typography.bodySm,
    color: colors.onMuted,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  reelSkeletonTile: {
    aspectRatio: 0.72,
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
  },
  reelSkeletonTileFeatured: {
    aspectRatio: 1.46,
  },
  loadingSources: {
    gap: spacing.md,
  },
  loadingSourcesTitle: {
    ...typography.labelLg,
    color: colors.onSurface,
  },
  loadingSourcesBody: {
    ...typography.bodySm,
    color: colors.onMuted,
  },
  loadingState: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.lg,
  },
  loadingText: {
    ...typography.bodySm,
    color: colors.onMuted,
  },
  reelTile: {
    aspectRatio: 0.72,
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    overflow: 'hidden',
  },
  reelTileFeatured: {
    aspectRatio: 1.46,
  },
  reelTileImage: {
    height: '100%',
    width: '100%',
  },
  reelTileScrim: {
    backgroundColor: 'rgba(16, 26, 23, 0.42)',
    bottom: 0,
    height: '54%',
    left: 0,
    position: 'absolute',
    right: 0,
  },
  latestBadge: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    left: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    position: 'absolute',
    top: spacing.sm,
  },
  latestBadgeText: {
    ...typography.labelMd,
    color: colors.onPrimary,
  },
  reelTileMeta: {
    bottom: spacing.md,
    gap: spacing.sm,
    left: spacing.md,
    position: 'absolute',
    right: spacing.md,
  },
  reelTileTitle: {
    ...typography.titleMd,
    color: colors.onPrimary,
  },
  reelCreator: {
    ...typography.caption,
    color: colors.onPrimary,
    opacity: 0.82,
  },
  processingDot: {
    backgroundColor: colors.warningSoft,
    borderColor: colors.warning,
    borderRadius: 9,
    borderWidth: 1,
    height: 18,
    position: 'absolute',
    right: spacing.sm,
    top: spacing.sm,
    width: 18,
  },
  attentionDot: {
    alignItems: 'center',
    backgroundColor: colors.errorSoft,
    borderColor: colors.error,
    borderRadius: 9,
    borderWidth: 1,
    height: 18,
    justifyContent: 'center',
    position: 'absolute',
    right: spacing.sm,
    top: spacing.sm,
    width: 18,
  },
  attentionText: {
    color: colors.error,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 13,
  },
  detailContent: {
    alignSelf: 'center',
    gap: spacing.lg,
    maxWidth: 430,
    padding: spacing.screen,
    paddingBottom: spacing.xxl,
    width: '100%',
  },
  detailNav: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  detailNavIdentity: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'center',
    minWidth: 0,
  },
  detailNavAvatar: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: 14,
    height: 28,
    width: 28,
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  backText: {
    ...typography.labelMd,
    color: colors.onSurface,
  },
  detailNavTitle: {
    ...typography.labelLg,
    color: colors.secondary,
    flex: 1,
    textAlign: 'center',
  },
  detailNavHandle: {
    ...typography.labelLg,
    color: colors.secondary,
    flexShrink: 1,
    minWidth: 0,
  },
  previewWrap: {
    alignItems: 'center',
    marginTop: spacing.xl,
  },
  sourceSummary: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.md,
    minHeight: 64,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  sourceSummaryImage: {
    aspectRatio: 9 / 16,
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.hairline,
    borderRadius: radius.sm,
    borderWidth: 1,
    height: 46,
    overflow: 'hidden',
  },
  sourceSummaryCopy: {
    flex: 1,
    gap: spacing.xxs,
    minWidth: 0,
  },
  sourceSummaryLabel: {
    ...typography.caption,
    color: colors.onMuted,
  },
  sourceSummaryCreator: {
    ...typography.labelLg,
    color: colors.onSurface,
  },
  sourceSummaryAction: {
    ...typography.labelMd,
    color: colors.primary,
  },
  sourceHero: {
    gap: spacing.md,
    marginTop: spacing.sm,
  },
  sourceHeroStage: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 392,
    overflow: 'visible',
    paddingVertical: spacing.lg,
  },
  sourceHeroPaper: {
    aspectRatio: 1.1,
    backgroundColor: colors.paper,
    borderColor: colors.paperEdge,
    borderRadius: radius.md,
    borderWidth: 1,
    opacity: 0.88,
    position: 'absolute',
    width: '88%',
  },
  sourceHeroCard: {
    aspectRatio: 9 / 16,
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.hairline,
    borderRadius: radius.lg,
    borderWidth: 1,
    overflow: 'hidden',
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.18,
    shadowRadius: 24,
  },
  sourceHeroImage: {
    height: '100%',
    width: '100%',
  },
  sourceHeroAction: {
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: colors.surfaceElevated,
    borderColor: colors.primary,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.xs,
    minHeight: 40,
    paddingHorizontal: spacing.md,
  },
  sourceHeroActionText: {
    ...typography.labelLg,
    color: colors.primary,
  },
  sourceHeroMeta: {
    gap: spacing.md,
  },
  sourceHeroIdentity: {
    alignItems: 'baseline',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  sourceHeroCreator: {
    ...typography.titleLg,
    color: colors.onSurface,
    flex: 1,
  },
  sourceHeroSavedAt: {
    ...typography.caption,
    color: colors.onMuted,
    flexShrink: 0,
  },
  originalSourceSection: {
    gap: spacing.md,
    marginTop: spacing.lg,
  },
  originalSourceTitle: {
    ...typography.titleLg,
    color: colors.onSurface,
  },
  originalSourceModule: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.md,
    padding: spacing.md,
  },
  originalSourcePreview: {
    aspectRatio: 9 / 16,
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.hairline,
    borderRadius: radius.md,
    borderWidth: 1,
    overflow: 'hidden',
  },
  reelPreviewImage: {
    height: '100%',
    width: '100%',
  },
  originalSourceCopy: {
    flex: 1,
    gap: spacing.md,
    justifyContent: 'space-between',
    minWidth: 0,
  },
  sourceCreator: {
    ...typography.labelLg,
    color: colors.onSurface,
  },
  detailSourceAction: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  sourceQuote: {
    backgroundColor: colors.sourceContextSoft,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.md,
    padding: spacing.md,
  },
  sourceQuoteLine: {
    backgroundColor: colors.primary,
    borderRadius: 1,
    width: 2,
  },
  sourceQuoteCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  sourceQuoteText: {
    ...typography.bodySm,
    color: colors.ink,
  },
  sourceQuoteAttribution: {
    ...typography.caption,
    color: colors.sourceContext,
  },
  section: {
    gap: spacing.md,
    marginTop: spacing.lg,
  },
  sectionTitle: {
    ...typography.headlineMd,
    color: colors.onSurface,
  },
  sectionSubtitle: {
    ...typography.bodySm,
    color: colors.onMuted,
  },
  bookList: {
    gap: spacing.md,
  },
  bookListSurface: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    overflow: 'hidden',
  },
  bookRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    minHeight: 112,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  bookRowDivider: {
    backgroundColor: colors.border,
    height: 1,
    marginLeft: spacing.md + 52 + spacing.md,
  },
  bookSpine: {
    alignItems: 'center',
    borderColor: colors.hairline,
    borderRadius: radius.sm,
    borderWidth: 1,
    height: 74,
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
    width: 52,
  },
  bookSpineText: {
    ...typography.labelMd,
    color: colors.onPrimary,
    textAlign: 'center',
  },
  bookSpineSkeleton: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.sm,
    height: 74,
    width: 52,
  },
  bookCover: {
    alignItems: 'center',
    borderRadius: radius.sm,
    height: 64,
    justifyContent: 'center',
    width: 44,
  },
  bookCoverText: {
    ...typography.labelMd,
    color: colors.onPrimary,
  },
  bookCoverImage: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.hairline,
    borderRadius: radius.sm,
    borderWidth: 1,
    height: 74,
    width: 52,
  },
  bookCopy: {
    flex: 1,
    gap: spacing.xs,
    minWidth: 0,
  },
  bookRowAction: {
    flexShrink: 0,
  },
  bookTitle: {
    ...typography.titleMd,
    color: colors.onSurface,
  },
  bookAuthor: {
    ...typography.bodySm,
    color: colors.secondary,
  },
  bookSynopsis: {
    ...typography.caption,
    color: colors.onMuted,
  },
  skeletonList: {
    gap: spacing.md,
  },
  skeletonCover: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.sm,
    height: 64,
    width: 44,
  },
  skeletonTextGroup: {
    flex: 1,
    gap: spacing.sm,
  },
  skeletonLine: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.xs,
    height: 10,
  },
  stateCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    gap: spacing.md,
    marginTop: spacing.lg,
    padding: spacing.lg,
  },
  stateTitle: {
    ...typography.titleLg,
    color: colors.onSurface,
  },
  stateBody: {
    ...typography.bodySm,
    color: colors.onMuted,
  },
  stateActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  pendingSourcePrompt: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  pendingSourceCopy: {
    gap: spacing.xs,
  },
  pendingSourceTitle: {
    ...typography.labelLg,
    color: colors.onSurface,
  },
  pendingSourceUrl: {
    ...typography.bodySm,
    color: colors.onMuted,
  },
  pendingSourceActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  statePreviewWrap: {
    alignItems: 'center',
    overflow: 'hidden',
  },
  emptyPreviewWrap: {
    alignItems: 'center',
    overflow: 'hidden',
    paddingVertical: spacing.sm,
  },
  tumbleweedWrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  tumbleweedShadow: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyScene: {
    alignItems: 'center',
    gap: spacing.md,
    marginTop: spacing.xxl,
    paddingHorizontal: spacing.lg,
  },
  emptySceneTitle: {
    ...typography.titleLg,
    color: colors.onSurface,
    marginTop: spacing.sm,
    textAlign: 'center',
  },
  emptySceneBody: {
    ...typography.bodySm,
    color: colors.onMuted,
    maxWidth: 280,
    textAlign: 'center',
  },
  emptySceneActions: {
    marginTop: spacing.sm,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    minHeight: 52,
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  primaryButtonText: {
    ...typography.labelLg,
    color: colors.onPrimary,
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  secondaryButtonText: {
    ...typography.labelLg,
    color: colors.onSurface,
  },
  compactButton: {
    minHeight: 40,
    paddingHorizontal: spacing.md,
  },
  disabledButton: {
    opacity: 0.55,
  },
  inlineMessage: {
    borderRadius: radius.md,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.md,
  },
  inlineError: {
    backgroundColor: colors.errorSoft,
    borderColor: colors.error,
  },
  inlineWarning: {
    backgroundColor: colors.warningSoft,
    borderColor: colors.warning,
  },
  inlineMessageText: {
    ...typography.bodySm,
  },
  inlineErrorText: {
    color: colors.error,
  },
  inlineWarningText: {
    color: colors.warning,
  },
  inlineAction: {
    alignSelf: 'flex-start',
  },
  inlineActionText: {
    ...typography.labelMd,
    color: colors.primary,
  },
  modalOverlay: {
    backgroundColor: 'rgba(20, 32, 27, 0.06)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  bottomSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    gap: spacing.lg,
    padding: spacing.screen,
    paddingBottom: spacing.xxl,
  },
  sheetHandle: {
    alignSelf: 'center',
    backgroundColor: colors.border,
    borderRadius: 2,
    height: 4,
    width: 42,
  },
  sheetTitle: {
    ...typography.headlineMd,
    color: colors.onSurface,
  },
  sheetBody: {
    ...typography.bodySm,
    color: colors.onMuted,
  },
  accountEmail: {
    ...typography.bodySm,
    color: colors.onMuted,
  },
  sheetBookSummary: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    gap: spacing.xs,
    padding: spacing.md,
  },
  sheetBookTitle: {
    ...typography.labelLg,
    color: colors.onSurface,
  },
  sheetBookAuthor: {
    ...typography.bodySm,
    color: colors.secondary,
  },
  sheetMenu: {
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    overflow: 'hidden',
  },
  sheetWarning: {
    backgroundColor: colors.errorSoft,
    borderRadius: radius.md,
    gap: spacing.xs,
    padding: spacing.md,
  },
  sheetWarningTitle: {
    ...typography.labelLg,
    color: colors.error,
  },
  sheetWarningBody: {
    ...typography.bodySm,
    color: colors.onSurface,
  },
  sheetRow: {
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  sheetRowText: {
    ...typography.bodyMd,
    color: colors.onSurface,
  },
  destructiveText: {
    color: colors.error,
  },
  inputLabel: {
    ...typography.labelMd,
    color: colors.secondary,
    marginBottom: spacing.xs,
    marginTop: spacing.sm,
  },
  input: {
    ...typography.bodyMd,
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    color: colors.onSurface,
    minHeight: 48,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.lg,
  },
  authProductPreview: {
    alignItems: 'center',
    alignSelf: 'center',
    height: 336,
    justifyContent: 'center',
    maxWidth: 352,
    overflow: 'visible',
    position: 'relative',
    width: '100%',
  },
  authProductPreviewCompact: {
    height: 296,
    maxWidth: 278,
  },
  authPreviewReelShell: {
    aspectRatio: 0.56,
    backgroundColor: colors.ink,
    borderColor: 'rgba(16, 26, 23, 0.20)',
    borderRadius: radius.lg,
    borderWidth: 1,
    boxShadow: '0 16px 30px rgba(16, 26, 23, 0.18)',
    overflow: 'hidden',
    width: 142,
    zIndex: 3,
  },
  authPreviewReelShellCompact: {
    borderRadius: radius.md,
    width: 116,
  },
  authPreviewReelImage: {
    height: '100%',
    width: '100%',
  },
  authPreviewReelMeta: {
    alignItems: 'center',
    bottom: spacing.sm,
    flexDirection: 'row',
    gap: spacing.xs,
    left: spacing.sm,
    position: 'absolute',
  },
  authPreviewReelPlay: {
    color: colors.onPrimary,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 16,
  },
  authPreviewReelCount: {
    color: colors.onPrimary,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 16,
  },
  authOrbitGuide: {
    borderColor: 'rgba(14, 111, 104, 0.22)',
    borderRadius: 999,
    borderWidth: 1,
    position: 'absolute',
  },
  authOrbitGuideOuter: {
    height: 212,
    transform: [{ rotate: '-10deg' }],
    width: 336,
  },
  authOrbitGuideOuterCompact: {
    height: 176,
    width: 262,
  },
  authOrbitGuideInner: {
    height: 176,
    opacity: 0.6,
    transform: [{ rotate: '14deg' }],
    width: 282,
  },
  authOrbitGuideInnerCompact: {
    height: 146,
    width: 218,
  },
  authOrbitBook: {
    position: 'absolute',
    zIndex: 4,
  },
  authOrbitBookUpperLeft: {
    left: 12,
    top: 24,
  },
  authOrbitBookUpperLeftCompact: {
    left: 4,
    top: 22,
  },
  authOrbitBookUpperRight: {
    right: 12,
    top: 42,
  },
  authOrbitBookUpperRightCompact: {
    right: 4,
    top: 38,
  },
  authOrbitBookLowerLeft: {
    bottom: 18,
    left: 12,
  },
  authOrbitBookLowerLeftCompact: {
    bottom: 18,
    left: 4,
  },
  authOrbitBookLowerRight: {
    bottom: 22,
    right: 12,
  },
  authOrbitBookLowerRightCompact: {
    bottom: 20,
    right: 4,
  },
  authOrbitBookCover: {
    alignItems: 'center',
    borderColor: 'rgba(16, 26, 23, 0.12)',
    borderRadius: radius.sm,
    borderWidth: 1,
    boxShadow: '0 9px 18px rgba(16, 26, 23, 0.14)',
    height: 94,
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.sm,
    width: 66,
  },
  authOrbitBookCoverPaper: {
    backgroundColor: '#EEE7D8',
  },
  authOrbitBookCoverGreen: {
    backgroundColor: '#0F302D',
  },
  authOrbitBookCoverOlive: {
    backgroundColor: '#4D5840',
  },
  authOrbitBookCoverCream: {
    backgroundColor: '#F0E8D8',
  },
  authOrbitBookTitle: {
    color: colors.ink,
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 13,
    textAlign: 'center',
  },
  authOrbitBookRule: {
    backgroundColor: 'rgba(16, 26, 23, 0.22)',
    height: 1,
    marginVertical: spacing.xs,
    width: 28,
  },
  authOrbitBookAuthor: {
    color: colors.inkMuted,
    fontSize: 8,
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 10,
    textAlign: 'center',
  },
  authOrbitBookTextLight: {
    color: colors.onPrimary,
  },
  authOrbitBookRuleLight: {
    backgroundColor: 'rgba(255, 255, 255, 0.34)',
  },
  productPreview: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'center',
  },
  previewReelCard: {
    aspectRatio: 0.62,
    backgroundColor: colors.book,
    borderColor: colors.hairline,
    borderRadius: radius.lg,
    borderWidth: 1,
    justifyContent: 'flex-end',
    overflow: 'hidden',
    padding: spacing.sm,
    width: 122,
  },
  previewImageWash: {
    backgroundColor: colors.secondary,
    bottom: 0,
    left: 0,
    opacity: 0.46,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  previewScrim: {
    backgroundColor: 'rgba(16, 26, 23, 0.42)',
    bottom: 0,
    height: '58%',
    left: 0,
    position: 'absolute',
    right: 0,
  },
  previewReelText: {
    ...typography.bodySm,
    color: colors.onPrimary,
  },
  previewCreator: {
    ...typography.caption,
    color: colors.onPrimary,
    marginTop: spacing.md,
    opacity: 0.82,
  },
  previewConnector: {
    alignItems: 'center',
    width: 22,
  },
  previewConnectorDot: {
    backgroundColor: colors.primary,
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  previewConnectorLine: {
    backgroundColor: colors.primary,
    height: 70,
    opacity: 0.5,
    width: 1,
  },
  previewBookStack: {
    gap: spacing.sm,
    width: 166,
  },
  previewBookLabel: {
    ...typography.caption,
    color: colors.onMuted,
    textAlign: 'center',
  },
  previewBookRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    padding: spacing.xs,
  },
  previewBookCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  previewBookTitle: {
    ...typography.labelMd,
    color: colors.ink,
  },
  previewBookAuthor: {
    ...typography.caption,
    color: colors.inkMuted,
  },
});
