import { StyleSheet } from 'react-native';

import { colors, radius, spacing, typography } from '@/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.neutral,
  },
  pressed: {
    transform: [{ scale: 0.98 }],
    opacity: 0.88,
  },
  authScreen: {
    flex: 1,
    justifyContent: 'space-between',
    padding: spacing.screen,
    paddingTop: spacing.xxl + spacing.xl,
    paddingBottom: spacing.xxl,
  },
  authMark: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  authMarkText: {
    ...typography.titleMd,
    color: colors.primary,
  },
  authCopy: {
    gap: spacing.md,
  },
  authBrand: {
    ...typography.labelLg,
    color: colors.secondary,
  },
  authTitle: {
    ...typography.headlineLg,
    color: colors.onSurface,
    maxWidth: 330,
  },
  authBody: {
    ...typography.bodyMd,
    color: colors.onMuted,
    maxWidth: 340,
  },
  authActions: {
    gap: spacing.md,
  },
  authLink: {
    alignSelf: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  authLinkText: {
    ...typography.labelMd,
    color: colors.secondary,
  },
  topNav: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  navBrand: {
    ...typography.labelLg,
    color: colors.secondary,
  },
  navActions: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  navSquareButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  navButtonText: {
    ...typography.labelLg,
    color: colors.onSurface,
  },
  profileButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 19,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  profileButtonText: {
    ...typography.labelLg,
    color: colors.onPrimary,
  },
  homeContent: {
    gap: spacing.xl,
    padding: spacing.screen,
    paddingBottom: spacing.xxl,
  },
  homeHeader: {
    gap: spacing.xs,
  },
  screenTitle: {
    ...typography.headlineLg,
    color: colors.onSurface,
  },
  screenSubtitle: {
    ...typography.bodySm,
    color: colors.onMuted,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  loadingState: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.lg,
  },
  loadingText: {
    ...typography.bodySm,
    color: colors.onMuted,
  },
  reelTile: {
    aspectRatio: 0.72,
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    overflow: 'hidden',
  },
  reelTileImage: {
    height: '100%',
    width: '100%',
  },
  reelTileScrim: {
    backgroundColor: 'rgba(20, 32, 27, 0.22)',
    bottom: 0,
    height: 54,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  reelCreator: {
    ...typography.caption,
    bottom: spacing.sm,
    color: colors.onPrimary,
    left: spacing.sm,
    position: 'absolute',
    right: spacing.sm,
  },
  processingDot: {
    backgroundColor: colors.warningSoft,
    borderColor: colors.warning,
    borderRadius: 9,
    borderWidth: 1,
    height: 18,
    position: 'absolute',
    right: spacing.sm,
    top: spacing.sm,
    width: 18,
  },
  attentionDot: {
    alignItems: 'center',
    backgroundColor: colors.errorSoft,
    borderColor: colors.error,
    borderRadius: 9,
    borderWidth: 1,
    height: 18,
    justifyContent: 'center',
    position: 'absolute',
    right: spacing.sm,
    top: spacing.sm,
    width: 18,
  },
  attentionText: {
    color: colors.error,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 13,
  },
  detailContent: {
    padding: spacing.screen,
    paddingBottom: spacing.xxl,
  },
  detailNav: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  backText: {
    ...typography.labelMd,
    color: colors.onSurface,
  },
  detailNavTitle: {
    ...typography.labelLg,
    color: colors.secondary,
    flex: 1,
    textAlign: 'center',
  },
  previewWrap: {
    alignItems: 'center',
    marginTop: spacing.xl,
  },
  reelPreview: {
    aspectRatio: 9 / 16,
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    overflow: 'hidden',
  },
  reelPreviewImage: {
    height: '100%',
    width: '100%',
  },
  sourceBlock: {
    alignItems: 'center',
    gap: spacing.xs,
    marginTop: spacing.lg,
    paddingHorizontal: spacing.md,
  },
  sourceCreator: {
    ...typography.labelLg,
    color: colors.onSurface,
  },
  sourceSnippet: {
    ...typography.bodySm,
    color: colors.onMuted,
    maxWidth: 330,
    textAlign: 'center',
  },
  section: {
    gap: spacing.md,
    marginTop: spacing.xxl,
  },
  sectionTitle: {
    ...typography.headlineMd,
    color: colors.onSurface,
  },
  bookList: {
    gap: spacing.md,
  },
  bookRow: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.md,
    padding: spacing.card,
  },
  bookCover: {
    alignItems: 'center',
    borderRadius: radius.sm,
    height: 64,
    justifyContent: 'center',
    width: 44,
  },
  bookCoverText: {
    ...typography.labelMd,
    color: colors.onPrimary,
  },
  bookCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  bookTitle: {
    ...typography.titleMd,
    color: colors.onSurface,
  },
  bookAuthor: {
    ...typography.bodySm,
    color: colors.secondary,
  },
  bookSynopsis: {
    ...typography.caption,
    color: colors.onMuted,
  },
  skeletonList: {
    gap: spacing.md,
  },
  skeletonCover: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.sm,
    height: 64,
    width: 44,
  },
  skeletonTextGroup: {
    flex: 1,
    gap: spacing.sm,
  },
  skeletonLine: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.xs,
    height: 10,
  },
  stateCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    gap: spacing.md,
    marginTop: spacing.xxl,
    padding: spacing.lg,
  },
  stateTitle: {
    ...typography.titleLg,
    color: colors.onSurface,
  },
  stateBody: {
    ...typography.bodySm,
    color: colors.onMuted,
  },
  stateActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  primaryButtonText: {
    ...typography.labelLg,
    color: colors.onPrimary,
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  secondaryButtonText: {
    ...typography.labelLg,
    color: colors.onSurface,
  },
  compactButton: {
    minHeight: 40,
    paddingHorizontal: spacing.md,
  },
  disabledButton: {
    opacity: 0.55,
  },
  inlineMessage: {
    borderRadius: radius.md,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.md,
  },
  inlineError: {
    backgroundColor: colors.errorSoft,
    borderColor: colors.error,
  },
  inlineWarning: {
    backgroundColor: colors.warningSoft,
    borderColor: colors.warning,
  },
  inlineMessageText: {
    ...typography.bodySm,
  },
  inlineErrorText: {
    color: colors.error,
  },
  inlineWarningText: {
    color: colors.warning,
  },
  inlineAction: {
    alignSelf: 'flex-start',
  },
  inlineActionText: {
    ...typography.labelMd,
    color: colors.primary,
  },
  modalOverlay: {
    backgroundColor: 'rgba(20, 32, 27, 0.18)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  bottomSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    gap: spacing.lg,
    padding: spacing.screen,
    paddingBottom: spacing.xxl,
  },
  sheetHandle: {
    alignSelf: 'center',
    backgroundColor: colors.border,
    borderRadius: 2,
    height: 4,
    width: 42,
  },
  sheetTitle: {
    ...typography.headlineMd,
    color: colors.onSurface,
  },
  sheetBody: {
    ...typography.bodySm,
    color: colors.onMuted,
  },
  accountEmail: {
    ...typography.bodySm,
    color: colors.onMuted,
  },
  sheetMenu: {
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    overflow: 'hidden',
  },
  sheetRow: {
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  sheetRowText: {
    ...typography.bodyMd,
    color: colors.onSurface,
  },
  destructiveText: {
    color: colors.error,
  },
  inputLabel: {
    ...typography.labelMd,
    color: colors.secondary,
    marginBottom: spacing.xs,
    marginTop: spacing.sm,
  },
  input: {
    ...typography.bodyMd,
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    color: colors.onSurface,
    minHeight: 48,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.lg,
  },
});
