import { StyleSheet } from 'react-native';

import { colors, radius, spacing, typography } from '@/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.neutral,
  },
  pressed: {
    transform: [{ scale: 0.98 }],
    opacity: 0.88,
  },
  surface: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
  },
  paperSurface: {
    backgroundColor: colors.paper,
    borderColor: colors.paperEdge,
  },
  raisedSurface: {
    backgroundColor: colors.surfaceElevated,
  },
  appMark: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  appMarkText: {
    color: colors.primaryPressed,
    fontSize: 28,
    fontWeight: '700',
    lineHeight: 32,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceElevated,
    borderColor: colors.border,
    borderRadius: 20,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  iconButtonFilled: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  iconButtonText: {
    ...typography.labelLg,
    color: colors.ink,
    lineHeight: 18,
  },
  iconCanvas: {
    alignItems: 'center',
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  iconStroke: {
    borderRadius: 1,
    position: 'absolute',
  },
  iconPlusHorizontal: {
    height: 2,
    width: 13,
  },
  iconPlusVertical: {
    height: 13,
    width: 2,
  },
  iconUserHead: {
    borderRadius: 5,
    borderWidth: 1.8,
    height: 9,
    width: 9,
  },
  iconUserBody: {
    borderRadius: 8,
    borderTopWidth: 1.8,
    height: 8,
    marginTop: 2,
    width: 15,
  },
  iconBackShaft: {
    borderRadius: 1,
    height: 2,
    left: 5,
    position: 'absolute',
    top: 10,
    width: 13,
  },
  iconBackUpper: {
    borderRadius: 1,
    height: 2,
    left: 4,
    position: 'absolute',
    top: 7,
    transform: [{ rotate: '-45deg' }],
    width: 9,
  },
  iconBackLower: {
    borderRadius: 1,
    height: 2,
    left: 4,
    position: 'absolute',
    top: 13,
    transform: [{ rotate: '45deg' }],
    width: 9,
  },
  iconMoreCanvas: {
    flexDirection: 'row',
    gap: 3,
  },
  iconDot: {
    borderRadius: 2,
    height: 4,
    width: 4,
  },
  authScreen: {
    alignSelf: 'center',
    flexGrow: 1,
    gap: spacing.xxl,
    justifyContent: 'space-between',
    maxWidth: 430,
    padding: spacing.screen,
    paddingTop: spacing.xxl + spacing.xl,
    paddingBottom: spacing.xxl,
    width: '100%',
  },
  authHero: {
    gap: spacing.xxxl,
  },
  authMark: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  authMarkText: {
    ...typography.titleMd,
    color: colors.primary,
  },
  authCopy: {
    gap: spacing.lg,
  },
  authBrand: {
    ...typography.labelLg,
    color: colors.secondary,
  },
  authTitle: {
    ...typography.display,
    color: colors.onSurface,
    maxWidth: 360,
  },
  authTitleSlot: {
    color: colors.primaryPressed,
  },
  authBody: {
    ...typography.bodyMd,
    color: colors.onMuted,
    maxWidth: 300,
  },
  authPreviewWrap: {
    alignItems: 'center',
  },
  authActions: {
    gap: spacing.md,
  },
  authLink: {
    alignSelf: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  authLinkText: {
    ...typography.labelMd,
    color: colors.secondary,
  },
  topNav: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  navBrand: {
    ...typography.titleMd,
    color: colors.primaryPressed,
  },
  navActions: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  navSquareButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  navButtonText: {
    ...typography.labelLg,
    color: colors.onSurface,
  },
  profileButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 19,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  profileButtonText: {
    ...typography.labelLg,
    color: colors.onPrimary,
  },
  homeContent: {
    alignSelf: 'center',
    gap: spacing.lg,
    maxWidth: 430,
    padding: spacing.screen,
    paddingBottom: spacing.xxl,
    width: '100%',
  },
  homeHeader: {
    gap: spacing.sm,
    paddingTop: spacing.sm,
  },
  screenTitle: {
    ...typography.headlineLg,
    color: colors.onSurface,
  },
  screenSubtitle: {
    ...typography.bodySm,
    color: colors.onMuted,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  reelSkeletonTile: {
    aspectRatio: 0.72,
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
  },
  reelSkeletonTileFeatured: {
    aspectRatio: 1.46,
  },
  loadingState: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.lg,
  },
  loadingText: {
    ...typography.bodySm,
    color: colors.onMuted,
  },
  reelTile: {
    aspectRatio: 0.72,
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    overflow: 'hidden',
  },
  reelTileFeatured: {
    aspectRatio: 1.46,
  },
  reelTileImage: {
    height: '100%',
    width: '100%',
  },
  reelTileScrim: {
    backgroundColor: 'rgba(16, 26, 23, 0.42)',
    bottom: 0,
    height: '54%',
    left: 0,
    position: 'absolute',
    right: 0,
  },
  latestBadge: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    left: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    position: 'absolute',
    top: spacing.sm,
  },
  latestBadgeText: {
    ...typography.labelMd,
    color: colors.onPrimary,
  },
  reelTileMeta: {
    bottom: spacing.md,
    gap: spacing.sm,
    left: spacing.md,
    position: 'absolute',
    right: spacing.md,
  },
  reelTileTitle: {
    ...typography.titleMd,
    color: colors.onPrimary,
  },
  reelCreator: {
    ...typography.caption,
    color: colors.onPrimary,
    opacity: 0.82,
  },
  processingDot: {
    backgroundColor: colors.warningSoft,
    borderColor: colors.warning,
    borderRadius: 9,
    borderWidth: 1,
    height: 18,
    position: 'absolute',
    right: spacing.sm,
    top: spacing.sm,
    width: 18,
  },
  attentionDot: {
    alignItems: 'center',
    backgroundColor: colors.errorSoft,
    borderColor: colors.error,
    borderRadius: 9,
    borderWidth: 1,
    height: 18,
    justifyContent: 'center',
    position: 'absolute',
    right: spacing.sm,
    top: spacing.sm,
    width: 18,
  },
  attentionText: {
    color: colors.error,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 13,
  },
  detailContent: {
    alignSelf: 'center',
    gap: spacing.lg,
    maxWidth: 430,
    padding: spacing.screen,
    paddingBottom: spacing.xxl,
    width: '100%',
  },
  detailNav: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  backText: {
    ...typography.labelMd,
    color: colors.onSurface,
  },
  detailNavTitle: {
    ...typography.labelLg,
    color: colors.secondary,
    flex: 1,
    textAlign: 'center',
  },
  previewWrap: {
    alignItems: 'center',
    marginTop: spacing.xl,
  },
  detailHero: {
    gap: spacing.lg,
  },
  previewPaper: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'transparent',
    borderRadius: radius.lg,
    padding: 0,
  },
  reelPreview: {
    aspectRatio: 9 / 16,
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.hairline,
    borderRadius: radius.lg,
    borderWidth: 1,
    overflow: 'hidden',
  },
  reelPreviewImage: {
    height: '100%',
    width: '100%',
  },
  sourceBlock: {
    gap: spacing.md,
  },
  sourceCreator: {
    ...typography.labelLg,
    color: colors.onSurface,
  },
  detailSourceAction: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  sourceQuote: {
    backgroundColor: colors.sourceContextSoft,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.md,
    padding: spacing.md,
  },
  sourceQuoteLine: {
    backgroundColor: colors.primary,
    borderRadius: 1,
    width: 2,
  },
  sourceQuoteCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  sourceQuoteText: {
    ...typography.bodySm,
    color: colors.ink,
  },
  sourceQuoteAttribution: {
    ...typography.caption,
    color: colors.sourceContext,
  },
  section: {
    gap: spacing.md,
    marginTop: spacing.lg,
  },
  sectionTitle: {
    ...typography.headlineMd,
    color: colors.onSurface,
  },
  sectionSubtitle: {
    ...typography.bodySm,
    color: colors.onMuted,
  },
  bookList: {
    gap: spacing.md,
  },
  bookRow: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.lg,
    padding: spacing.card,
  },
  bookSpine: {
    alignItems: 'center',
    borderColor: colors.hairline,
    borderRadius: radius.sm,
    borderWidth: 1,
    height: 74,
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
    width: 52,
  },
  bookSpineText: {
    ...typography.labelMd,
    color: colors.onPrimary,
    textAlign: 'center',
  },
  bookSpineSkeleton: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.sm,
    height: 74,
    width: 52,
  },
  bookCover: {
    alignItems: 'center',
    borderRadius: radius.sm,
    height: 64,
    justifyContent: 'center',
    width: 44,
  },
  bookCoverText: {
    ...typography.labelMd,
    color: colors.onPrimary,
  },
  bookCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  bookTitle: {
    ...typography.titleMd,
    color: colors.onSurface,
  },
  bookAuthor: {
    ...typography.bodySm,
    color: colors.secondary,
  },
  bookSynopsis: {
    ...typography.caption,
    color: colors.onMuted,
  },
  skeletonList: {
    gap: spacing.md,
  },
  skeletonCover: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.sm,
    height: 64,
    width: 44,
  },
  skeletonTextGroup: {
    flex: 1,
    gap: spacing.sm,
  },
  skeletonLine: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.xs,
    height: 10,
  },
  stateCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    gap: spacing.md,
    marginTop: spacing.lg,
    padding: spacing.lg,
  },
  stateTitle: {
    ...typography.titleLg,
    color: colors.onSurface,
  },
  stateBody: {
    ...typography.bodySm,
    color: colors.onMuted,
  },
  stateActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  pendingSourcePrompt: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  pendingSourceCopy: {
    gap: spacing.xs,
  },
  pendingSourceTitle: {
    ...typography.labelLg,
    color: colors.onSurface,
  },
  pendingSourceUrl: {
    ...typography.bodySm,
    color: colors.onMuted,
  },
  pendingSourceActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  statePreviewWrap: {
    alignItems: 'center',
    overflow: 'hidden',
  },
  emptyPreviewWrap: {
    alignItems: 'center',
    overflow: 'hidden',
    paddingVertical: spacing.sm,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    minHeight: 52,
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  primaryButtonText: {
    ...typography.labelLg,
    color: colors.onPrimary,
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  secondaryButtonText: {
    ...typography.labelLg,
    color: colors.onSurface,
  },
  compactButton: {
    minHeight: 40,
    paddingHorizontal: spacing.md,
  },
  disabledButton: {
    opacity: 0.55,
  },
  inlineMessage: {
    borderRadius: radius.md,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.md,
  },
  inlineError: {
    backgroundColor: colors.errorSoft,
    borderColor: colors.error,
  },
  inlineWarning: {
    backgroundColor: colors.warningSoft,
    borderColor: colors.warning,
  },
  inlineMessageText: {
    ...typography.bodySm,
  },
  inlineErrorText: {
    color: colors.error,
  },
  inlineWarningText: {
    color: colors.warning,
  },
  inlineAction: {
    alignSelf: 'flex-start',
  },
  inlineActionText: {
    ...typography.labelMd,
    color: colors.primary,
  },
  modalOverlay: {
    backgroundColor: 'rgba(20, 32, 27, 0.06)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  bottomSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    gap: spacing.lg,
    padding: spacing.screen,
    paddingBottom: spacing.xxl,
  },
  sheetHandle: {
    alignSelf: 'center',
    backgroundColor: colors.border,
    borderRadius: 2,
    height: 4,
    width: 42,
  },
  sheetTitle: {
    ...typography.headlineMd,
    color: colors.onSurface,
  },
  sheetBody: {
    ...typography.bodySm,
    color: colors.onMuted,
  },
  accountEmail: {
    ...typography.bodySm,
    color: colors.onMuted,
  },
  sheetMenu: {
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    overflow: 'hidden',
  },
  sheetRow: {
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  sheetRowText: {
    ...typography.bodyMd,
    color: colors.onSurface,
  },
  destructiveText: {
    color: colors.error,
  },
  inputLabel: {
    ...typography.labelMd,
    color: colors.secondary,
    marginBottom: spacing.xs,
    marginTop: spacing.sm,
  },
  input: {
    ...typography.bodyMd,
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    color: colors.onSurface,
    minHeight: 48,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.lg,
  },
  productPreview: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'center',
  },
  previewReelCard: {
    aspectRatio: 0.62,
    backgroundColor: colors.book,
    borderColor: colors.hairline,
    borderRadius: radius.lg,
    borderWidth: 1,
    justifyContent: 'flex-end',
    overflow: 'hidden',
    padding: spacing.sm,
    width: 122,
  },
  previewImageWash: {
    backgroundColor: colors.secondary,
    bottom: 0,
    left: 0,
    opacity: 0.46,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  previewScrim: {
    backgroundColor: 'rgba(16, 26, 23, 0.42)',
    bottom: 0,
    height: '58%',
    left: 0,
    position: 'absolute',
    right: 0,
  },
  previewReelText: {
    ...typography.bodySm,
    color: colors.onPrimary,
  },
  previewCreator: {
    ...typography.caption,
    color: colors.onPrimary,
    marginTop: spacing.md,
    opacity: 0.82,
  },
  previewConnector: {
    alignItems: 'center',
    width: 22,
  },
  previewConnectorDot: {
    backgroundColor: colors.primary,
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  previewConnectorLine: {
    backgroundColor: colors.primary,
    height: 70,
    opacity: 0.5,
    width: 1,
  },
  previewBookStack: {
    gap: spacing.sm,
    width: 166,
  },
  previewBookLabel: {
    ...typography.caption,
    color: colors.onMuted,
    textAlign: 'center',
  },
  previewBookRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    padding: spacing.xs,
  },
  previewBookCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  previewBookTitle: {
    ...typography.labelMd,
    color: colors.ink,
  },
  previewBookAuthor: {
    ...typography.caption,
    color: colors.inkMuted,
  },
});
