export const colors = {
  primary: '#0E6F68',
  primaryPressed: '#094C48',
  primarySoft: '#DDF5F1',
  onPrimary: '#FFFFFF',
  secondary: '#4E5D57',
  tertiary: '#2F4A44',
  neutral: '#F7F5F0',
  neutralDeep: '#ECE7DD',
  surface: '#FFFFFF',
  surfaceMuted: '#F1EEE6',
  surfaceElevated: '#FFFEFA',
  paper: '#F4EFE5',
  paperEdge: '#DCD4C6',
  onSurface: '#101A17',
  onMuted: '#69706A',
  ink: '#101A17',
  inkMuted: '#69706A',
  border: '#DDD7CC',
  hairline: 'rgba(16, 26, 23, 0.10)',
  book: '#2F4A44',
  bookSoft: '#E7ECE5',
  sourceContext: '#405B55',
  sourceContextSoft: '#E9EDE7',
  warning: '#8A5E00',
  warningSoft: '#FFF3D6',
  success: '#17643C',
  successSoft: '#E5F6EA',
  error: '#B42318',
  errorSoft: '#FDE7E4',
};

export const spacing = {
  xxs: 2,
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  xxl: 32,
  xxxl: 44,
  screen: 20,
  card: 16,
};

export const radius = {
  xs: 4,
  sm: 6,
  md: 10,
  lg: 16,
  xl: 24,
};

export const typography = {
  display: {
    fontSize: 44,
    lineHeight: 45,
    fontWeight: '700' as const,
    letterSpacing: 0,
  },
  headlineLg: {
    fontSize: 34,
    lineHeight: 37,
    fontWeight: '700' as const,
    letterSpacing: 0,
  },
  headlineMd: {
    fontSize: 24,
    lineHeight: 28,
    fontWeight: '700' as const,
    letterSpacing: 0,
  },
  titleLg: {
    fontSize: 20,
    lineHeight: 25,
    fontWeight: '600' as const,
    letterSpacing: 0,
  },
  titleMd: {
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '600' as const,
    letterSpacing: 0,
  },
  bodyMd: {
    fontSize: 16,
    lineHeight: 23,
    fontWeight: '400' as const,
    letterSpacing: 0,
  },
  bodySm: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400' as const,
    letterSpacing: 0,
  },
  labelLg: {
    fontSize: 14,
    lineHeight: 17,
    fontWeight: '600' as const,
    letterSpacing: 0,
  },
  labelMd: {
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '600' as const,
    letterSpacing: 0,
  },
  caption: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '400' as const,
    letterSpacing: 0,
  },
};
